class BillRunner{

    public static void main(String bill[]){
	
	    //ClassName ref = new ClassName();
		Bill ref = new Bill();
		
	    System.out.println("ref billReferenceId started");
		int billReferenceId = ref.billReferenceId;
		System.out.println(billReferenceId);
		billReferenceId = 1;
		System.out.println(billReferenceId);
		billReferenceId = 2;
		System.out.println(billReferenceId);
		billReferenceId = 3;
		System.out.println(billReferenceId);
		billReferenceId = 4;
		System.out.println(billReferenceId);
		billReferenceId = 5;
		System.out.println(billReferenceId);
		billReferenceId = 6;
		System.out.println(billReferenceId);
		billReferenceId = 7;
		System.out.println(billReferenceId);
		billReferenceId = 8;
		System.out.println(billReferenceId);
		billReferenceId = 9;
		System.out.println(billReferenceId);
		billReferenceId = 10;
		System.out.println(billReferenceId);
		System.out.println("ref billReferenceId ended");
		
		System.out.println("ref billSequenceNo started");
		int billSequenceNo = ref.billSequenceNo;
		System.out.println(billSequenceNo);
		billSequenceNo = 11;
		System.out.println(billSequenceNo);
		billSequenceNo = 12;
		System.out.println(billSequenceNo);
		billSequenceNo = 13;
		System.out.println(billSequenceNo);
		billSequenceNo = 14;
		System.out.println(billSequenceNo);
		billSequenceNo = 15;
		System.out.println(billSequenceNo);
		billSequenceNo = 16;
		System.out.println(billSequenceNo);
		billSequenceNo = 17;
		System.out.println(billSequenceNo);
		billSequenceNo = 18;
		System.out.println(billSequenceNo);
		billSequenceNo = 19;
		System.out.println(billSequenceNo);
		billSequenceNo = 20;
		System.out.println(billSequenceNo);
		System.out.println("ref billSequenceNo ended");
		
		System.out.println("ref billIssueDate started");
		String billIssueDate = ref.billIssueDate;
		billIssueDate = "29/06/2024";
		System.out.println(billIssueDate);
		billIssueDate = "30/06/2024";
		System.out.println(billIssueDate);
		billIssueDate = "01/07/2024";
		System.out.println(billIssueDate);
		billIssueDate = "05/07/2024";
		System.out.println(billIssueDate);
		billIssueDate = "08/07/2024";
		System.out.println(billIssueDate);
		billIssueDate = "10/07/2024";
		System.out.println(billIssueDate);
		billIssueDate = "12/07/2024";
		System.out.println(billIssueDate);
		billIssueDate = "15/07/2024";
		System.out.println(billIssueDate);
		billIssueDate = "20/07/2024";
		System.out.println(billIssueDate);
		billIssueDate = "28/07/2024";
		System.out.println(billIssueDate);
	    System.out.println("ref billIssueDate started");
		
		System.out.println("ref billDueDate started");
		String billDueDate = ref.billDueDate;
		billDueDate = "01/07/2024";
		System.out.println(billDueDate);
		billDueDate = "05/07/2024";
		System.out.println(billDueDate);
		billDueDate = "10/07/2024";
		System.out.println(billDueDate);
		billDueDate = "25/07/2024";
		System.out.println(billDueDate);
		billDueDate = "30/07/2024";
		System.out.println(billDueDate);
		billDueDate = "01/08/2024";
		System.out.println(billDueDate);
		billDueDate = "07/08/2024";
		System.out.println(billDueDate);
		billDueDate = "10/08/2024";
		System.out.println(billDueDate);
		billDueDate = "18/08/2024";
		System.out.println(billDueDate);
		System.out.println("ref billDueDate ended");
		
		System.out.println("ref isBillPaid started");
		boolean isBillPaid = ref.isBillPaid;
		isBillPaid = true;
		System.out.println(isBillPaid);
		isBillPaid = false;
		System.out.println(isBillPaid);
		isBillPaid = true;
		System.out.println(isBillPaid);
		isBillPaid = true;
		System.out.println(isBillPaid);
		isBillPaid = false;
		System.out.println(isBillPaid);
		isBillPaid = true;
		System.out.println(isBillPaid);
		isBillPaid = false;
		System.out.println(isBillPaid);
		isBillPaid = true;
		System.out.println(isBillPaid);
		isBillPaid = false;
		System.out.println(isBillPaid);
		isBillPaid = true;
		System.out.println(isBillPaid);
		System.out.println("ref isBillPaid ended");
		
		System.out.println("ref isLatestBill started");
		boolean isLatestBill = ref.isLatestBill;
		isLatestBill = false;
		System.out.println(isLatestBill);
		isLatestBill = true;
		System.out.println(isLatestBill);
		isLatestBill = false;
		System.out.println(isLatestBill);
		isLatestBill = true;
		System.out.println(isLatestBill);
		isLatestBill = false;
		System.out.println(isLatestBill);
		isLatestBill = true;
		System.out.println(isLatestBill);
		isLatestBill = false;
		System.out.println(isLatestBill);
		isLatestBill = false;
		System.out.println(isLatestBill);
		isLatestBill = true;
		System.out.println(isLatestBill);
		isLatestBill = true;
		System.out.println(isLatestBill);
		isLatestBill = false;
		System.out.println(isLatestBill);
		System.out.println("ref isLatestBill ended");
		
		System.out.println("ref isFinalBill started");
		boolean isFinalBill = ref.isFinalBill;
		isFinalBill = true;
		System.out.println(isFinalBill);
		isFinalBill = true;
		System.out.println(isFinalBill);
		isFinalBill = false;
		System.out.println(isFinalBill);
		isFinalBill = false;
		System.out.println(isFinalBill);
		isFinalBill = true;
		System.out.println(isFinalBill);
		isFinalBill = true;
		System.out.println(isFinalBill);
		isFinalBill = false;
		System.out.println(isFinalBill);
		isFinalBill = true;
		System.out.println(isFinalBill);
		isFinalBill = false;
		System.out.println(isFinalBill);
		isFinalBill = true;
		System.out.println(isFinalBill);
		System.out.println("ref isFinalBill ended");
		
		System.out.println("ref billAmount started");
		double billAmount = ref.billAmount;
		billAmount = 200.89;
		System.out.println(billAmount);
		billAmount = 267.00;
		System.out.println(billAmount);
		billAmount = 290.09;
		System.out.println(billAmount);
		billAmount = 400.00;
		System.out.println(billAmount);
		billAmount = 200.9;
		System.out.println(billAmount);
		billAmount = 450.15;
		System.out.println(billAmount);
		billAmount = 600.56;
		System.out.println(billAmount);
		billAmount = 255.98;
		System.out.println(billAmount);
		billAmount = 278.8;
		System.out.println(billAmount);
		billAmount = 444.99;
		System.out.println(billAmount);
		billAmount = 550.00;
		System.out.println(billAmount);
		System.out.println("ref billAmount ended");
		
		System.out.println("ref taxInclusiveBill started");
		boolean taxInclusiveBill = ref.taxInclusiveBill;
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = false;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = false;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = false;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = false;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = true;
		System.out.println(taxInclusiveBill);
		taxInclusiveBill = false;
		System.out.println(taxInclusiveBill);
		System.out.println("ref taxInclusiveBill ended");
		
	}

}